CREATE TABLE userDashboard (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_name TEXT NOT NULL,
    title TEXT NOT NULL,
    doggoaddress TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    date_modified TIMESTAMPTZ DEFAULT now() NOT NULL,
    FOREIGN KEY(user_name) REFERENCES doggoUser(user_name) ON DELETE CASCADE

);


